POST http://localhost:3001/api/journals
Content-Type: application/json

{
	"date": "2020-04-12",
	"todos": [
		{
			"id": 1,
			"task": "Learn React for two hours",
			"done": true
		},
		{
			"id": 2,
			"task": "Practice skating for one hour",
			"done": true
		}
	],
	"reflection": "Today is good.",
	"book_summaries": [
		{
			"id": 1,
			"title": "Catch-22",
			"chapter": "The Texan",
			"content": "This chapter is very interesting. This chapter is very interesting. This chapter is very interesting. This chapter is very interesting. This chapter is very interesting."
		}
	],
	"words_of_today": [],
	"userId": "5e98524c11597145b0aaffe2"
}